---
ID: "b1fc39a8-5b58-401c-a698-a5f263154e74"
Parent: "6f5ed323-f3e8-4187-9c01-d5f6ea7bf1ff"
Template: "6f5ed323-f3e8-4187-9c01-d5f6ea7bf1ff"
Path: /sitecore/templates/Project/DevanshiK_BasicSite/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240619T075031Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f70de7c9-fbe0-4935-93e4-336b0677eef7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240619T075031Z
